/**
 * BriefComposer
 *
 * Two-tier daily news brief generation:
 *   Tier 1 - Programmatic topic clustering via keyword intersection (no LLM)
 *   Tier 2 - Lightweight LLM enrichment for top stories (Synthesizer-only calls)
 *
 * The brief is cached 24h in Redis. Lazy-generated on first read if missing
 * (Render free tier), or pre-generated by the worker (Docker mode).
 */

import { fetchAllNewsCached } from "../../scraper.js";
import type { ScrapedArticle, MarketBrief, BriefStory } from "../../src/types.js";
import { getCachedBrief, setCachedBrief, getCachedFinancialBrief, setCachedFinancialBrief } from "./cache.js";
import { childLogger } from "./logger.js";

const log = childLogger({ module: "brief-composer" });

//
// Constants
//

const STOP_WORDS = new Set([
  "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
  "of", "with", "by", "from", "as", "is", "was", "are", "were", "be",
  "been", "being", "have", "has", "had", "do", "does", "did", "will",
  "would", "can", "could", "should", "may", "might", "shall", "its",
  "it's", "their", "they", "them", "this", "that", "these", "those",
  "what", "which", "who", "whom", "when", "where", "why", "how", "all",
  "each", "every", "both", "few", "more", "most", "some", "any", "no",
  "not", "only", "own", "same", "so", "than", "too", "very", "just",
  "about", "above", "after", "again", "against", "below", "between",
  "into", "over", "under", "up", "down", "out", "off", "then", "once",
  "here", "there",
]);

const MIN_STORY_KEYWORDS = 3;   // minimum shared keywords to cluster
const MAX_STORIES = 5;          // top stories to include in brief

//
// Tier 1: Programmatic clustering
//

function tokenize(title: string): string[] {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
}

interface ArticleCluster {
  keywords: Set<string>;
  articles: ScrapedArticle[];
  sources: Set<string>;
}

function clusterArticles(articles: ScrapedArticle[]): ArticleCluster[] {
  const clusters: ArticleCluster[] = [];

  for (const article of articles) {
    const tokens = tokenize(article.title);
    if (tokens.length === 0) continue;

    // Find the best cluster match
    let bestMatch: ArticleCluster | null = null;
    let bestOverlap = 0;

    for (const cluster of clusters) {
      const overlap = tokens.filter((t) => cluster.keywords.has(t)).length;
      if (overlap > bestOverlap) {
        bestOverlap = overlap;
        bestMatch = cluster;
      }
    }

    if (bestMatch && bestOverlap >= MIN_STORY_KEYWORDS) {
      bestMatch.articles.push(article);
      for (const t of tokens) bestMatch.keywords.add(t);
      bestMatch.sources.add(article.source);
    } else {
      clusters.push({
        keywords: new Set(tokens),
        articles: [article],
        sources: new Set([article.source]),
      });
    }
  }

  return clusters;
}

function rankClusters(clusters: ArticleCluster[]): ArticleCluster[] {
  return clusters
    .sort((a, b) => {
      // Primary sort: number of distinct sources
      const sourceDiff = b.sources.size - a.sources.size;
      if (sourceDiff !== 0) return sourceDiff;
      // Secondary sort: article count
      return b.articles.length - a.articles.length;
    })
    .slice(0, MAX_STORIES);
}

function clusterTitle(keywords: Set<string>, articles: ScrapedArticle[]): string {
  // Use the most common article title that contains the most keywords
  const scored = articles
    .map((a) => ({
      title: a.title,
      score: tokenize(a.title).filter((t) => keywords.has(t)).length,
    }))
    .sort((a, b) => b.score - a.score);

  return scored[0]?.title ?? articles[0]?.title ?? "Untitled Story";
}

//
// Tier 2: LLM enrichment (Synthesizer-only call)
//

const BRIEF_ENRICH_PROMPT = `You are a Cross-Source Media Synthesis Specialist for the Trinidad News Comparer system. Your task is to produce a concise framing divergence note for a single story covered by multiple Trinidad & Tobago news outlets.

Given a story title and article headlines grouped by source, produce a JSON object with:
1. framingDivergence: A single sentence describing how the outlets differed in their framing
2. perSourceAngles: Array of {sourceName, angle, articleUrl} showing each outlet's approach
3. sourceAgreementLevel: "high", "medium", or "low"

Focus on journalistic framing differences, not political bias. Be specific.`;

interface BriefEnrichResult {
  framingDivergence: string;
  perSourceAngles: Array<{ sourceName: string; angle: string; articleUrl?: string }>;
  sourceAgreementLevel: "high" | "medium" | "low";
}

function buildSourceGroup(cluster: ArticleCluster): string {
  const bySource = new Map<string, ScrapedArticle[]>();
  for (const a of cluster.articles) {
    const arr = bySource.get(a.source) ?? [];
    arr.push(a);
    bySource.set(a.source, arr);
  }
  return [...bySource.entries()]
    .map(([src, arts]) =>
      `--- ${src} ---\n${arts.map((a) => `- "${a.title}" (${a.link})`).join("\n")}`
    )
    .join("\n\n");
}

/**
 * Enrich a cluster with LLM-determined framing divergence.
 */
async function enrichCluster(
  cluster: ArticleCluster,
  nvidiaClassifier?: (prompt: string) => Promise<string>,
): Promise<BriefStory> {
  const title = clusterTitle(cluster.keywords, cluster.articles);
  const defaultAngles = [...cluster.sources].map((s) => ({
    sourceName: s,
    angle: `Covered ${title}`,
  }));

  if (!nvidiaClassifier) {
    return {
      storyTitle: title,
      framingDivergence: `Covered by ${cluster.sources.size} source(s).`,
      perSourceAngles: defaultAngles,
      sourceAgreementLevel: cluster.sources.size > 1 ? "medium" : "high",
    };
  }

  try {
    const sourceGroup = buildSourceGroup(cluster);
    const prompt = `${BRIEF_ENRICH_PROMPT}\n\nStory:\n${title}\n\nCoverage:\n${sourceGroup}\n\nOutput JSON:`;
    const result = await nvidiaClassifier(prompt);
    const cleaned = result.replace(/```(?:json)?\s*([\s\S]*?)```/, "$1").trim();
    const parsed = JSON.parse(cleaned) as BriefEnrichResult;

    return {
      storyTitle: title,
      framingDivergence: parsed.framingDivergence || `Covered by ${cluster.sources.size} source(s).`,
      perSourceAngles: parsed.perSourceAngles?.length
        ? parsed.perSourceAngles.map((a) => ({
            sourceName: a.sourceName,
            angle: a.angle,
            articleUrl: a.articleUrl,
          }))
        : defaultAngles,
      sourceAgreementLevel: ["high", "medium", "low"].includes(parsed.sourceAgreementLevel ?? "")
        ? parsed.sourceAgreementLevel as "high" | "medium" | "low"
        : "medium",
    };
  } catch (err) {
    log.warn({ err: (err as Error).message, title }, "Brief enrichment LLM failed, using programmatic fallback");
    return {
      storyTitle: title,
      framingDivergence: `Covered by ${cluster.sources.size} source(s).`,
      perSourceAngles: defaultAngles,
      sourceAgreementLevel: cluster.sources.size > 1 ? "medium" : "high",
    };
  }
}

//
// Main entry: generate the daily brief
//

export async function generateBrief(
  nvidiaClassifier?: (prompt: string) => Promise<string>,
): Promise<MarketBrief> {
  const articles = await fetchAllNewsCached();
  const now = new Date();

  log.info({ totalArticles: articles.length }, "Generating daily brief");

  if (articles.length === 0) {
    const brief: MarketBrief = {
      generatedAt: now.toISOString(),
      windowStart: new Date(now.getTime() - 86400000).toISOString(),
      windowEnd: now.toISOString(),
      topStories: [],
      editorNote: "No news coverage found in the current window.",
    };
    await setCachedBrief(brief);
    return brief;
  }

  // Tier 1: Programmatic clustering
  const clusters = clusterArticles(articles);
  const topClusters = rankClusters(clusters);

  if (topClusters.length === 0) {
    const brief: MarketBrief = {
      generatedAt: now.toISOString(),
      windowStart: new Date(now.getTime() - 86400000).toISOString(),
      windowEnd: now.toISOString(),
      topStories: [],
      editorNote: "No significant cross-source stories identified.",
    };
    await setCachedBrief(brief);
    return brief;
  }

  // Tier 2: Enrich the top 1-2 stories with LLM
  const [primary, ...rest] = topClusters;
  const enriched = await enrichCluster(primary, nvidiaClassifier);

  // For the rest, use programmatic only
  const remainingStories: BriefStory[] = rest.map((c) => ({
    storyTitle: clusterTitle(c.keywords, c.articles),
    framingDivergence: `Covered by ${c.sources.size} source(s).`,
    perSourceAngles: [...c.sources].map((s) => ({ sourceName: s, angle: `Reported on this story.` })),
    sourceAgreementLevel: c.sources.size > 1 ? "medium" : "high" as "high" | "medium" | "low",
  }));

  const brief: MarketBrief = {
    generatedAt: now.toISOString(),
    windowStart: new Date(now.getTime() - 86400000).toISOString(),
    windowEnd: now.toISOString(),
    topStories: [enriched, ...remainingStories],
    editorNote:
      "This brief is generated by the Trinidad News Comparer system. It identifies top stories by cross-source coverage volume and highlights framing differences. Always read the original articles for full context.",
  };

  await setCachedBrief(brief);
  log.info({ stories: brief.topStories.length }, "Brief generated and cached");
  return brief;
}

/**
 * Get the latest cached brief, generating one if missing (lazy generation).
 */
export async function getOrGenerateBrief(
  nvidiaClassifier?: (prompt: string) => Promise<string>,
): Promise<MarketBrief | null> {
  const cached = await getCachedBrief<MarketBrief>();
  if (cached) return cached;
  return generateBrief(nvidiaClassifier);
}

//
// Phase 2: Financial brief
//

const FINANCIAL_BRIEF_ENRICH_PROMPT = `You are a Financial Market Analyst for the Trinidad News Comparer system. Given a financial topic and coverage from multiple sources, produce a JSON object with:
1. framingDivergence: A single sentence describing how sources differed in their financial framing
2. perSourceAngles: Array of {sourceName, angle, articleUrl}
3. sourceAgreementLevel: "high", "medium", or "low"
4. keyMetrics: Array of {metric, value, period} extracted from the coverage

Focus on factual financial data, not opinion.`;

/**
 * Generate the financial brief.
 * Requires financial articles from dedicated scrapers (TTSE, Central Bank).
 */
export async function generateFinancialBrief(
  financialArticles: ScrapedArticle[],
  nvidiaClassifier?: (prompt: string) => Promise<string>,
): Promise<MarketBrief> {
  const now = new Date();
  log.info({ totalArticles: financialArticles.length }, "Generating financial brief");

  if (financialArticles.length === 0) {
    const brief: MarketBrief = {
      generatedAt: now.toISOString(),
      windowStart: new Date(now.getTime() - 86400000).toISOString(),
      windowEnd: now.toISOString(),
      topStories: [],
      editorNote: "No financial coverage found in the current window.",
    };
    await setCachedFinancialBrief(brief);
    return brief;
  }

  const clusters = clusterArticles(financialArticles);
  const topClusters = rankClusters(clusters);

  if (topClusters.length === 0) {
    const brief: MarketBrief = {
      generatedAt: now.toISOString(),
      windowStart: new Date(now.getTime() - 86400000).toISOString(),
      windowEnd: now.toISOString(),
      topStories: [],
      editorNote: "No significant financial stories identified.",
    };
    await setCachedFinancialBrief(brief);
    return brief;
  }

  const stories: BriefStory[] = await Promise.all(
    topClusters.map(async (c) => {
      const title = clusterTitle(c.keywords, c.articles);
      if (!nvidiaClassifier) {
        return {
          storyTitle: title,
          framingDivergence: `Covered by ${c.sources.size} source(s).`,
          perSourceAngles: [...c.sources].map((s) => ({ sourceName: s, angle: `Reported on this financial story.` })),
          sourceAgreementLevel: c.sources.size > 1 ? "medium" : "high",
        };
      }
      try {
        const sourceGroup = buildSourceGroup(c);
        const prompt = `${FINANCIAL_BRIEF_ENRICH_PROMPT}\n\nStory:\n${title}\n\nCoverage:\n${sourceGroup}\n\nOutput JSON:`;
        const result = await nvidiaClassifier(prompt);
        const cleaned = result.replace(/```(?:json)?\s*([\s\S]*?)```/, "$1").trim();
        const parsed = JSON.parse(cleaned) as BriefEnrichResult;
        return {
          storyTitle: title,
          framingDivergence: parsed.framingDivergence || `Covered by ${c.sources.size} source(s).`,
          perSourceAngles: parsed.perSourceAngles?.length
            ? parsed.perSourceAngles.map((a) => ({ sourceName: a.sourceName, angle: a.angle, articleUrl: a.articleUrl }))
            : [...c.sources].map((s) => ({ sourceName: s, angle: `Reported on this story.` })),
          sourceAgreementLevel: ["high", "medium", "low"].includes(parsed.sourceAgreementLevel ?? "")
            ? parsed.sourceAgreementLevel as "high" | "medium" | "low"
            : "medium",
        };
      } catch {
        return {
          storyTitle: title,
          framingDivergence: `Covered by ${c.sources.size} source(s).`,
          perSourceAngles: [...c.sources].map((s) => ({ sourceName: s, angle: `Reported on this financial story.` })),
          sourceAgreementLevel: c.sources.size > 1 ? "medium" : "high",
        };
      }
    }),
  );

  const brief: MarketBrief = {
    generatedAt: now.toISOString(),
    windowStart: new Date(now.getTime() - 86400000).toISOString(),
    windowEnd: now.toISOString(),
    topStories: stories,
    editorNote: "Financial brief generated by the Trinidad News Comparer system. Market data sourced from publicly available financial news. Verify critical numbers against official filings.",
  };

  await setCachedFinancialBrief(brief);
  log.info({ stories: brief.topStories.length }, "Financial brief generated and cached");
  return brief;
}


